[package]
name = "weave"
version = "0.1.0"
edition = "2024"
description = "Deterministic execution for reproducible debugging"
license = "MIT"
readme = "README.md"
repository = "https://github.com/penberg/weave"
homepage = "https://github.com/penberg/weave"

[[bin]]
name = "weave"
path = "main.rs"

[lib]
name = "weave"
path = "lib.rs"

[dependencies]
goblin = "0.9"
intervaltree = "0.2.7"
libc = "0.2.172"
linkme = "0.3"
macros = { path = "macros" }
thiserror = "2.0.12"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[target.'cfg(target_arch = "aarch64")'.dependencies]
disarm64 = "0.1.24"

[target.'cfg(target_arch = "x86_64")'.dependencies]
iced-x86 = "1.21"

[profile.release]
codegen-units = 16

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
